### ISSUE TITLE
(docs) duplicate section slug/name "Rendering" cause both section to trigger

### ISSUE THREAD

**Issue by xstevenyung** [solidjs/solid-site#106]
There is currently 2 "Rendering" section in the documentation

When toggling one of them, both with open/close because they share the same slug, which can be confusing when navigating the documentation

Maybe one of the two sections should be renamed to avoid this issue ?

**Comment by davedbase** [comment]
We actually have a task to separate the guides and regular documentation sections. That should sort out the issue.
