### ISSUE TITLE
Stores/Create Store tutorial doesn't mention changes to JSX

### ISSUE THREAD

**Issue by jeremycook** [solidjs/solid-site#110]
I had to click Solve on the The Stores/Create Store tutorial to see what I was overlooking since the instructions weren't enough. The part that was left out was that `todos` in the JSX needed to be changed to `store.todos`. In hindsight that makes perfect sense but given this is the first intro to Stores it would help to spell that out.

See: /public/tutorial/lessons/stores_createstore/lesson.md

**Comment by davedbase** [comment]
Thanks! I flagged this and the `on` suggestion. We'll looking into making it happen =)
