### ISSUE TITLE
Add arabic translation 

### ISSUE THREAD

**Issue by MidouWebDev** [solidjs/solid-site#127]

**Comment by davedbase** [comment]
@MidouWebDev we haven't heard from you in a while? Do you plan on jumping in the French/Arabic translations for us?

**Comment by MidouWebDev** [comment]
Sure, i will. I was just facing a problem with my laptop but i will do my best to be back soon to complete the french and arabic translation

**Comment by MidouWebDev** [comment]
@davedbase sure, i hope i can be working on it tomorrow.
Don't worry, it is me who is going to handle this.

**Comment by upq** [comment]
where is that? I can't see it anywhere ..
