### ISSUE TITLE
Add dark mode on SolidJS website

### ISSUE THREAD

**Issue by trivikr** [solidjs/solid-site#129]
### Is your feature request related to a problem? Please describe.
The website https://www.solidjs.com/ does not have a dark mode.

### Describe the solution you'd like
* Add dark mode for the website.
* Automatically load a dark or light theme based on system preferences.
* Allow the user to manually override their preference using a toggle in the title/navigation bar, and maintain preferred theme between page reloads.

### Describe alternatives you've considered
* Reduce brightness of the screen while reading SolidJS website.
* Use a browser extension to enforce dark mode on the website.
* Revisit the website in the mornings when system has light mode enabled.

**Comment by trivikr** [comment]
Tailwind CSS includes [a `dark` variant](https://tailwindcss.com/docs/dark-mode) that allows styling site differently when dark mode is enabled.

**Comment by trivikr** [comment]
cc @amoutonbrady for comments, as they have been active in this repo.

**Comment by trivikr** [comment]
Solid playground already has a dark mode.

<details>
<summary>Screen recording</summary>

https://user-images.githubusercontent.com/16024985/129825112-201f54b4-392e-4346-98b0-b5869209e733.mov

</details>

It was added in https://github.com/solidjs/solid-playground/pull/47
cc @aquaductape who added dark mode to the Playground for comments.

**Comment by davedbase** [comment]
Yup I'd love to add this to the Solid website for consistency with Playground. We'd happily accept a PR to make it functional. I'd then likely be somewhat picky about colours and proper use of branded assets but the first step is to get the button in place and working with the Tailwind dark variant.
