### ISSUE TITLE
Problems with RTL

### ISSUE THREAD

**Issue by orenelbaum** [solidjs/solid-site#142]
I found these problems with RTL:
- The hero section background needs to be flipped.
- In the playground link in the navbar, the work playground is too close to the external link icon.
- Also in the header, the Github and Twitter links are too close.
- In the hero section and in the footer, the text is aligned to the left.
- In the footer:
  - The English words mess up the whole text.
  - The background should probably be flipped.
  - The sponsor links are left to right.
  - The text "Sponsored by" is missing.
- In the homepage, the arrow mark next to the links is partly on top of the links instead of to their left.
- The text editors in the homepage and in the example page don't actually show the code.
- In the docs, resources, examples and media pages, the page title is aligned to the left.
- In the resources page:
  - the text in the resource listings are still in English but they are in RTL and it messes it up. Number and punctuation are not of the correct side of the text.
  - In the resource types and categories, the text is aligned to the left.
- In the color list in the media page, the color samples are to the right of the color RGB value (not sure if that's intended), and they doesn't have any space between them.

**Comment by davedbase** [comment]
All patched and viewable on the dev site.
