### ISSUE TITLE
Russian & Portuguese website translation

### ISSUE THREAD

**Issue by davedbase** [solidjs/solid-site#143]
We're hoping to launch an updated Solid website (viewable on https://dev.solidjs.com) that includes not just doc translations, but the entire Solid site. We're only missing Russian and Portuguese right now.

@pheianox and @candidosales you both contributed to the docs I was wondering if you had a moment to handle a very small amount of translations for the site. The docs requiring translation are here: https://github.com/solidjs/solid-site/tree/dev/lang

We can't launch the new site without them unfortunately, so hoping you can help us out =) I'd be very appreciative.

**Comment by pheianox** [comment]
Wow, that's a great thing. Always happy to help. I'm starting now.

**Comment by pheianox** [comment]
PR #145

**Comment by davedbase** [comment]
Thanks for the help on Portuguese and Russian everyone =) we're live with this now.
