### ISSUE TITLE
Markup and Editor Sometimes Fail to Load

### ISSUE THREAD

**Issue by Jutanium** [solidjs/solid-site#144]
<img width="2093" alt="Screen Shot 2021-09-11 at 8 36 13 PM" src="https://user-images.githubusercontent.com/4033662/132966912-8ca2b836-08aa-461d-bf12-f53c5c506521.png">

You can reproduce this by repeatedly clicking the Tutorial button in the navbar.

**Comment by davedbase** [comment]
This has been patched on the latest release!
