### ISSUE TITLE
Tutorial lesson selector does not close after selection

### ISSUE THREAD

**Issue by fictitious** [solidjs/solid-site#158]
Started happening after the Sep 21 update from the dev branch with router updated to 0.1.5, i18n updates etc.

I tried to debug - clicking on `NavLink` list item changes the route, `DirectoryMenu` receives the new `current` item in props, firing the [effect that calls](https://github.com/solidjs/solid-site/blob/master/src/pages/Tutorial.tsx#L61) `setShowDirectory(false)`, but it looks like the [listContainer](https://github.com/solidjs/solid-site/blob/master/src/pages/Tutorial.tsx#L122) that should receive `hidden` class is not re-rendered. 

Clicking on the  [`<button>`](https://github.com/solidjs/solid-site/blob/master/src/pages/Tutorial.tsx#L103) with chevron that shows/hides `DirectoryMenu` directly without involving route change works.

**Comment by davedbase** [comment]
Thanks for letting us know. Actually looks like the "Solve" button was regressed as well but I've at least managed to patch that. Haven't had a chance to dig into the dropdown yet. Thanks for reporting this.

**Comment by fictitious** [comment]
The dropdown starts working again if I downgrade solid-js version to 1.1.0. Which makes me think that it's related to [this change](https://github.com/solidjs/solid/commit/d946cfeb3cc42f39bad4b665a984e6be6f14b284).

**Comment by ryansolid** [comment]
There were some bugs there but hopefully they are all fixed by 1.1.5.

**Comment by davedbase** [comment]
The production site was deployed last night on 1.1.5 so the issue with the dropdown seems to be unresolved.
