### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'scrollIntoView')

### ISSUE THREAD

**Issue by pheianox** [solidjs/solid-site#160]
If you just visit [this lnk](https://www.solidjs.com/docs/latest/api#6.-i-really-dislike-jsx%2C-any-chance-of-a-template-dsl%3F-oh%2C-i-see-you-have-tagged-template-literals%2Fhyperscript.-maybe-i-will-use-those) it kinda brokes the whole Solid Site, the site loses interactivity. I think it's because it cannot find that thing in the url section.  But if you open up the console you'll see this error that says
> Uncaught (in promise) TypeError: Cannot read properties of null (reading 'scrollIntoView')

LINK: https://www.solidjs.com/docs/latest/api#6.-i-really-dislike-jsx%2C-any-chance-of-a-template-dsl%3F-oh%2C-i-see-you-have-tagged-template-literals%2Fhyperscript.-maybe-i-will-use-those

**Comment by davedbase** [comment]
Ah thanks for reporting. This should be an easy fix.

**Comment by davedbase** [comment]
Seems like it works at the link https://www.solidjs.com/docs/latest/api#6.-i-really-dislike-jsx%2C-any-chance-of-a-template-dsl%3F-oh%2C-i-see-you-have-tagged-template-literals%2Fhyperscript.-maybe-i-will-use-those...

I'll close it for now. Also that's a silly link subsection title haha.
