### ISSUE TITLE
Can’t scroll navigation on mobile

### ISSUE THREAD

**Issue by eyelidlessness** [solidjs/solid-site#163]
I’m unable to scroll the navigation popup menu on mobile (iOS 14, Safari, iPhone 8 Plus in case any of that matters). I’m pretty sure this worked before, so it may be a regression.

I’m happy to look into contributing a fix, but probably won’t have bandwidth to look until this weekend.

**Comment by davedbase** [comment]
Hi there, thanks for you report! I'm having trouble replicating this myself. Do you mean the horizontal nav? Mind sending a screenshot so we're ok the same page. Thanks!

**Comment by eyelidlessness** [comment]
Oof sorry, no, I meant the docs nav. Video attached.

https://user-images.githubusercontent.com/199830/135501380-e0e7e365-a1e9-41f6-a21a-d4250cbe69a2.MP4

**Comment by davedbase** [comment]
Aha. Right! Thanks for clearing that up. We will have a look!

**Comment by davedbase** [comment]
A patch for this was just released =) thanks again.
