### ISSUE TITLE
A broken resource link

### ISSUE THREAD

**Issue by bobaekang** [solidjs/solid-site#164]
A link to video titled "React Wednesdays: Let's Learn Solid JS with Ryan Carniato" is broken (unavailable Twitch video): https://github.com/solidjs/solid-site/blob/f4c4ea4ec0dfca3aa6b566b4c2750dc40dbc9153/src/pages/Resources/Videos.data.ts#L118-L128

Here's a working link to the same resource on Kendo UI's YouTube channel: https://www.youtube.com/watch?v=cFasysKU7vk. Since React Wednesday is [presented by KendoReact](https://www.telerik.com/react-wednesdays), which is part of Kendo UI, the YouTube channel may as well be considered an official source.

**Comment by davedbase** [comment]
Thanks for pointing this out, I've gone ahead and corrected the reference.
