### ISSUE TITLE
[WIP] Sidebar design and implementation

### ISSUE THREAD

**Issue by davedbase** [solidjs/solid-site#196]
I'm starting to consider how to improve documentation page rendering and to make this component agnostic of the docs so that it can be used on various pages throughout Solid Site. The following is a rendering of how I plan to implement it for the documentation and guide pages, which will be the only ones to use it for now.

Here's an example of the sidebar for documentation:

<img width="1644" alt="Screen Shot 2021-11-21 at 2 44 31 PM" src="https://user-images.githubusercontent.com/1168397/142777908-357bbdfd-d89d-4845-b2bc-fb17e6be9ec6.png">

Here's an example of sidebar for guides:

<img width="1624" alt="Screen Shot 2021-11-21 at 2 55 51 PM" src="https://user-images.githubusercontent.com/1168397/142778112-1c00c831-da67-44b2-8a6e-05f13c446a21.png">

The improvements I was hoping to bring with this design:

1. Larger navigation elements
2. Fully open navigation (no expand/collapse mechanic)
3. Three level support

I'm rather sold on the aesthetic however if anyone has any suggestions/concerns, kindly let me know. We'll try to schedule this in once we migrate the website to Solid Start.

**Comment by atk** [comment]
You should probably add a scrolling indicator to show that there's stuff further down.

**Comment by davedbase** [comment]
Yup, that should kick in automatically because Caleb already added it to the site. So we got that covered.

**Comment by davedbase** [comment]
Joe suggested we have the ability to show/hide the left hand sidebar.
