### ISSUE TITLE
[hack.solidjs.com] broken playground link

### ISSUE THREAD

**Issue by AdvTechnoKing** [solidjs/solid-site#224]
1)
![image](https://user-images.githubusercontent.com/17812651/148688471-8d214188-378f-4255-8dcf-e866e3024ad7.png)

2)
![image](https://user-images.githubusercontent.com/17812651/148688434-23865b26-4442-45b5-88a6-62313c4a7386.png)

3)
![image](https://user-images.githubusercontent.com/17812651/148688494-30947431-50fc-408b-aa57-0a3b73903e35.png)

**Comment by davedbase** [comment]
Fixed!
