### ISSUE TITLE
UI :  the menu button is misaligned in docs  page(mobile view)

### ISSUE THREAD

**Issue by ghulamyazdani** [solidjs/solid-site#226]
In the docs page, the menu button is going out of the bound.

![image](https://user-images.githubusercontent.com/55938346/148755801-76e7bc8d-4958-48b9-84b1-6ce345b618bb.png)

Can be solved by aligning it in the header section

**Comment by davedbase** [comment]
Hmmm, I don't see this issue at all. Can you describe how I can replicate it?

**Comment by atk** [comment]
I believe it only appears in Chrome on Android on some versions.
