### ISSUE TITLE
Some issues I found surfing the website

### ISSUE THREAD

**Issue by AlidotSal** [solidjs/solid-site#235]
Main website:
  1. [ ] In Tutorial section, The expanded view Doesn't look good on wide screens. It's not bad on medium sizes (768px - 1000px) but for bigger than 
that, everything looks way too much stretched (code blocks are most annoying lol). 
  2. [x] Also adding syntax highlighting to code blocks in tutorial page would be a good idea.
  3. [ ] Between  ``lg`` and ``xl`` breakpoints(1024px - 1280px), Guides/Docs pages aren't well designed (too much empty space on the sides) .
  4. [ ] Navigation dropdown menu on touch screen doesn't go away after it's activated.
  5. [ ] About sub-nav causes overflow on small screens.

Dev version:
  - [x] In Guides/Docs pages there's a ``f`` in the arrow button (small screens), I'm not sure if it's intentional (or maybe it is, what do I know).
Dark mode:
  1. [x] ScrollShadow's color is black which shouldn't.
  2. [x] box shadows on features section.
  3. [x] Code blocks in Guides/Docs have white background which defeats the purpose. 
  4. [x] When you are in any page other than main page, hovering over nav links causes something awkward to happen (background of the current route changes not the one you are hovering over).
  5. [x] The background image on the page (below) in dark mode is so distracting.
 
![solid](https://user-images.githubusercontent.com/73060676/153254332-554e5184-3b6c-4456-a105-8e30c340d6b5.png)

**Comment by davedbase** [comment]
Thanks so much for putting these into an issue! I just resolved a little more than half of these and prompted other team members to help resolve the rest. :-)

**Comment by edemaine** [comment]
Might I suggest one of you edits the root post to use checkboxes (`1. [x]` or `1. [ ]`) so that it's clear which aren't resolved (in case you want help resolving those)?

**Comment by Dohxis** [comment]
I have implemented a syntax highlighting as per your suggestion as well #238.

**Comment by AlidotSal** [comment]
@edemaine I edited the post to reflect solved issues.

**Comment by davedbase** [comment]
As far as I can tell these issues are now resolved :-) thanks everyone! You're all incredible and we're so fortunate to have you part of this community.
