### ISSUE TITLE
Can't change tabs in tutorial code

### ISSUE THREAD

**Issue by CoolOppo** [solidjs/solid-site#273]
E.g.: https://www.solidjs.com/tutorial/stores_immutable

![image](https://user-images.githubusercontent.com/1498177/164977384-e849ee45-38f4-4796-aafc-4794679ebb37.png)

**Comment by davedbase** [comment]
This is now patched. I apologize this took a bit of time. Please re-open the issue if you continue having trouble. You might have to refresh the REPL when it pops up in the bottom left corner.
