### ISSUE TITLE
Unergonomic scrolling (mobile) with code examples

### ISSUE THREAD

**Issue by vincentvandijck** [solidjs/solid-site#305]
I am having some problems scrolling down on mobile when there are scroll-examples. The monospaced, unwrapped text causes the container to have a horizontal scrollbar which hijacks the vertical scrolling too, causing the page to stop scrolling down when my finger tries to swipe up over this code-container. This is especially annoying when there are big pieces of code covering the whole screen.

My finger gets back control over the scroll of the page when I scroll up, or scroll perfectly down. Both are quite unergonomic.

**Comment by davedbase** [comment]
Thanks for the report, we'll have someone look into it shortly!

**Comment by vincentvandijck** [comment]
I just checked the docs again on mobile and encountered no issues!  So thank you for the fix if you changed some code, or else I guess it was my phone bugging out 🤣 Anyway I will close this issue!
