### ISSUE TITLE
Adding Arabic locale

### ISSUE THREAD

**Issue by upq** [solidjs/solid-site#326]
Hello, I have git cloned the solid site to read and play with the code, I changed it a lot and I didn't create a fork in the first place, however one of the results of me playing around was adding Arabic to the languages supported, I'm sorry I cant create a pull request, so I created a gist that has all the necessary files to add the language support here

https://gist.github.com/upq/6c52d28ab97b088f844f16041d7aec9f

Thanks and have a good one.

**Comment by davedbase** [comment]
Thank you! Sorry for the delay in responding to this! We will make sure to add it as soon as we get a chance!

**Comment by mkwsra** [comment]
OMG, I am so sorry I didn't know there is an Arabic translation, I only checked the PRs, and when I didn't find any I went ahead and translated it and created a new PR. I wish I knew @upq I would have taken yours and saved myself sometime 😅

Anyways I hope you guys accept it. Thanks!

**Comment by high1** [comment]
#409 was merged, closing as completed. Thanks!
