### ISSUE TITLE
Support Palestine 

### ISSUE THREAD

**Issue by yousefelgoharyx** [solidjs/solid-site#366]
Is it possible to put a banner supporting Palestine since it's under attack now from Isreal and people are dying 
I want to raise people's awareness about the Palestinian case

**Comment by davedbase** [comment]
Yousuf, thank you for this message. I appreciate you drawing attention to this topic.

The situation in Israel and Palestine is a difficult and deeply divisive one. All people involved in the conflict have our deepest compassion and should remain in our thoughts as we strive to bring about international peace and order.

Our goal with the Ukraine message was to align with the broader JS community in a stance against international war. It's the most recent global scale attack on human rights and general stability of the international community. In hindsight this messaging could have been broader and more appreciative of the fact that all conflict is harmful.

I believe an appropriate approach is to broaden the message to reflect a general anti-war/anti-conflict sentiment. I propose to change the copy to 'Solid stands against war in Ukraine and all global conflict' with a link to https://www.un.org/en/globalceasefire. The Global Ceasefire link IMO is a very appropriate message that we'd like to communicate to our visitors.

This change will go up shortly. Thank you very much for helping making our community safer and more accessible.
