### ISSUE TITLE
[Comparison Page]. Sentence is cut off at the end.

### ISSUE THREAD

**Issue by shiba-sama** [solidjs/solid-site#401]
1. Observe this link: https://www.solidjs.com/guides/comparison#advice-for-migrating
2. The first sentence has words cut off from the end:
> Solid's update model is nothing like React, or even React + MobX. Instead of thinking of function components as the render function, think of them as a .

**Comment by high1** [comment]
This was a subtle bug in solid-jsx, fixed with https://github.com/solidjs/solid-docs/issues/175.
