### ISSUE TITLE
Gordita web font has "off center" vertical baseline

### ISSUE THREAD

**Issue by dstotijn** [solidjs/solid-site#411]
I think there's an issue with the bundled Gordita web font files on `solid-site`. The vertical baseline seems off-center, which you can see in the menu items and outlined buttons. I ran `solid-site` locally, and replaced the .woff files with the versions from the author's website (https://typeatelier.com/wp-content/themes/gillettstudio/fonts-dist/). This seems to fix it — no CSS changes required.

This "before and after" GIF should make it more clear what the issue is (note: it doesn't autoplay on GitHub, there should be a play icon on the top right of the image).

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/983924/204156476-3317fda3-1641-4f57-b146-d2ed5bdd705f.gif)

I'm happy to make a PR, although I couldn't find the .ttf and .eot files on the aforementioned URL; ideally we would replace those as well.

**Comment by davedbase** [comment]
Thanks for making us aware of this! The font has now been updated and looks considerably better with the proper baseline. :-)
