### ISSUE TITLE
Subtotal is Showing NaN

### ISSUE THREAD

**Issue by rahulbhadja** [solidjs/solid-site#419]
The solid store is not showing subtotal in number, instead, it is showing the NaN. see the image attached below.
<img width="779" alt="Screenshot 2022-12-20 at 5 53 21 PM" src="https://user-images.githubusercontent.com/41661703/208782518-4a7b0dcb-4578-4b9d-a7cd-16c6b5b18220.png">

**Comment by rahulbhadja** [comment]
created a pr -  https://github.com/solidjs/solid-site/pull/420

**Comment by high1** [comment]
#420 was merged, closing as completed, thanks!
