### ISSUE TITLE
Dark mode Select dropdown having white background in Store page

### ISSUE THREAD

**Issue by lutaok** [solidjs/solid-site#439]
Hello everyone,
I don't know if it's intentional but it seemed to me that `<select>` node dropdown doesn't have a fitting background for dark mode.

Playing a bit with dev-tools, seems that adding `dark:bg-solid-darkbg` to the `<select>` element solves the issue.

I'll attach a screenshot to show what I mean:
![solidjs-select-issue](https://user-images.githubusercontent.com/101177974/218194071-361667f0-6799-485d-beab-b3878248d0f7.jpeg)
Thank you for the amazing project, I'll gladly help out with a PR if you'd like me to open one 😄 .

P.S: I've also noticed that the remove button (appearing after adding an item to the cart) doesn't actually remove the item from the cart. The only way to do that is to open the cart popup and remove it from there. Should I open a separate issue about this for tracking purposes?

**Comment by davedbase** [comment]
Thanks for finally tackling this. Although we're redeveloping it's great to know someone has these sorts of issues tackled.
