### ISSUE TITLE
Introduction/Signals tutorial does not work in Firefox

### ISSUE THREAD

**Issue by lectrician1** [solidjs/solid-site#451]
https://www.solidjs.com/tutorial/introduction_signals?solved does not show changes to the count in the Result window in Firefox 113.0a1, however, it works in Chrome, and in Firefox when it is pasted to the Playground.

**Comment by modderme123** [comment]
This sounds like a phantom timing issue that no longer seems to be a problem, closing because I can't seem to reproduce this
