### ISSUE TITLE
Thoughts from running through the tutorials

### ISSUE THREAD

**Issue by martinpengellyphillips** [solidjs/solid-site#46]
Just took a look through the tutorial. Reads well and clearly I think - great job! Some other notes I made along the way:

* The first page has a `Solve` button but there is nothing to solve. Might be worth hiding. Also, might be worth explicitly calling out to navigate to the next step.
* Moving to the next step doesn't scroll instructions back to the top (at least in Firefox Windows). So it's a little awkward.
* I agree that the first SVG example might benefit from a code comment. Someone might naively try to copy the code into the Result pane as that most clearly says "SVG goes here"
* The `Solve` button is a big call to action button. But really it is the `Next` button that should be emphasised (as the solve is just an escape hatch in a tutorial really). Consider toning down solve and emphasising next.
* On that note - once they solve it by writing code, is there a way to detect that and give feedback. E.g. 'Great job, head to the next step!'

**Comment by ryansolid** [comment]
Thanks for the feedback.
 > The first page has a Solve button but there is nothing to solve. Might be worth hiding. Also, might be worth explicitly calling out to navigate to the next step.
 
This gives me an idea. I think I should actually call out the solve the same way you mention with the navigation. Technically the text changes. While there is nothing for them to do I think getting used to where the buttons are and how to use the tutorial makes a lot of sense. Everyone should click solve on that page before they move on etc.

> Moving to the next step doesn't scroll instructions back to the top (at least in Firefox Windows). So it's a little awkward.
Yep I'm pretty sure it's cross browser and platform. Noticed the same. We should fix that.

> I agree that the first SVG example might benefit from a code comment. Someone might naively try to copy the code into the Result pane as that most clearly says "SVG goes here"

This is great. The things you don't notice when you focus on the code. I was thinking that it was clearly stating to add the code here not recognizing it shows up both places on the page and much more prominently in the preview panel.

> The Solve button is a big call to action button. But really it is the Next button that should be emphasised (as the solve is just an escape hatch in a tutorial really). Consider toning down solve and emphasising next.

Maybe. This high emphasis is found on other tutorials like Svelte. I think there is some amount of expectation that users won't actually do the tutorial and just click solve. I do think next probably could use more emphasis. Maybe the word `next` written out. Probably more important than having a back.

> On that note - once they solve it by writing code, is there a way to detect that and give feedback. E.g. 'Great job, head to the next step!'

That's a cool idea. I guess it would look at the output? Input trimmed whitespace maybe.. It might be difficult to get it right and those gaps could build unfulfilled expectation. I think it would be really motivating though if it were possible.

**Comment by mosheduminer** [comment]
> That's a cool idea. I guess it would look at the output? Input trimmed whitespace maybe.. It might be difficult to get it right and those gaps could build unfulfilled expectation. I think it would be really motivating though if it were possible.

It might be worth looking at how freecodecamp does this. They seem to have a suite of tests that make sure you got the code right, before marking a lesson as "complete".

**Comment by seneca** [comment]
I've noticed that Lesson Bindings/Attributes has no corresponding lesson. It's possible that this is still in the works. Just wanted to flag it.

**Comment by davedbase** [comment]
Thanks for the notes on the docs everyone. Closing this out now.
