### ISSUE TITLE
Hompage advanced intro video broken link

### ISSUE THREAD

**Issue by benalleng** [solidjs/solid-site#461]
## Describe the bug

The advanced intro link (10 minutes) has been taken down as of 10/5/23 20:49 UTC

Expected youtube link:
https://www.youtube.com/watch?v=J70HXl1KhWE

**Comment by hsk-kr** [comment]
I can't find the video from the link. It seems that the video is not available anymore. I'm not able to find any videos with a keyword 'Solid reactivity in 10 minutes'.

**Comment by davedbase** [comment]
Unfortunately the YouTube videos were deleted by a former community member. I have copies of some of them however we're evaluating if they will be uploaded again.

**Comment by FeldrinH** [comment]
In the meantime it might be a good idea to remove links to this video from the website. It is displayed quite prominently in https://www.solidjs.com/guides/getting-started

**Comment by jcramb** [comment]
Just ran into this same issue and came looking to see if an issue existed... is there anything we can do to help getting this link removed / replaced?

**Comment by edemaine** [comment]
@davedbase If you update solid-docs to 1.0.53, the link should be removed (perhaps as a temporary fix).

**Comment by AlexErrant** [comment]
Here's the old 10m one for posterity https://www.youtube.com/watch?v=akWuo_aK2Zs
