### ISSUE TITLE
Delete the political discussion on the site

### ISSUE THREAD

**Issue by azchatlanin** [solidjs/solid-site#525]
### Stop campaigning and direct your efforts to create and develop this project.

Dear repository holders. Your project is open source. This means that people with different views on some problems contribute to its development. You don't need to use their work and the product itself to promote your political preferences. 

For some reason, you didn't shout these slogans much, for years Ukrainians killed and burned Russian children when the United States bombed Iraq, when they bombed Yugoslavia, or when Jews are killing children in Gaza now. 

Stop campaigning and direct your efforts to create and develop this project.

**Comment by birkskyum** [comment]
This post never was about OSS. I've reported the incident to GH.

**Comment by azchatlanin** [comment]
> Sad to see Russian propaganda finds it's way to GH. I've reported the incident.

First of all, why didn't you write a complaint that the owners of the project are engaged in Ukrainian propaganda?

Secondly, I just ask the owners to write code here, and not engage in any propaganda at all and remove their veiled call for violence and murder of the Russian population from the site.

**Comment by birkskyum** [comment]
GitHub got back to me with this message:

> If you have write permissions to a repository, you can hide, edit, or delete comments by using the tools described here:
>  
> [Managing disruptive comments](https://docs.github.com/en/github/building-a-strong-community/managing-disruptive-comments)
>  
> Additionally, users with admin permissions in a repository can permanently delete an issue from a repository by following these instructions:
>  
> [Deleting an issue](https://docs.github.com/en/github/managing-your-work-on-github/deleting-an-issue)
>  
> Keep in mind, you may block users at any time by following the steps outlined in either of the articles below.
>  
> [Blocking a user from your organization](https://docs.github.com/en/github/building-a-strong-community/blocking-a-user-from-your-organization)

Since 4 of these shell GitHub accounts have been in here and liking the OP since my comment yesterday, despite no engagement for the preceding 3 weeks since creation, this appear to be an organised information operation.

GitHub basically threw the ball right back in our court, and I guess their advice of blocking the users from the org / deleting the created issues are the best tools at hand, even though the it doesn't protect against new issues like it in any way.

**Comment by azchatlanin** [comment]
> GitHub got back to me with this message:
> 
> > If you have write permissions to a repository, you can hide, edit, or delete comments by using the tools described here:
> > [Managing disruptive comments](https://docs.github.com/en/github/building-a-strong-community/managing-disruptive-comments)
> > Additionally, users with admin permissions in a repository can permanently delete an issue from a repository by following these instructions:
> > [Deleting an issue](https://docs.github.com/en/github/managing-your-work-on-github/deleting-an-issue)
> > Keep in mind, you may block users at any time by following the steps outlined in either of the articles below.
> > [Blocking a user from your organization](https://docs.github.com/en/github/building-a-strong-community/blocking-a-user-from-your-organization)
> 
> Since 4 of these shell GitHub accounts have been in here and liking the OP since my comment yesterday, despite no engagement for the preceding 3 weeks since creation, this appear to be an organised information operation.
> 
> GitHub basically threw the ball right back in our court, and I guess their advice of blocking the users from the org / deleting the created issues are the best tools at hand, even though the it doesn't protect against new issues like it in any way.

I'll repeat it again. I'm just asking you not to engage in political propaganda on a site that is the result of the work of hundreds of programmers with different views.

But for some reason you didn't notice this propaganda, and you decided to mark my statement as propaganda.

That's your whole point. As you were two-faced, so you remain.

And you're right, I also think that the only right decision is to block you as a  of defenders of terrorism.

**Comment by atk** [comment]
> I'm just asking you not to engage in political propaganda on a site that is the result of the work of hundreds of programmers with different views.

Do you know (m)any of the involved programmers personally and can prove that their views are different? What you are actually asking us it to take your blanket statement at face value and censor a message of peace that was the result of a discussion with the core maintainers and members of the ecosystem team.

I believe that your claims have no merit, and your further framing of our message and ad hominems at our team member do not strenghen your case.

**Comment by azchatlanin** [comment]
> > I'm just asking you not to engage in political propaganda on a site that is the result of the work of hundreds of programmers with different views.
> 
> Do you know (m)any of the involved programmers personally and can prove that their views are different? What you are actually asking us it to take your blanket statement at face value and censor a message of peace that was the result of a discussion with the core maintainers and members of the ecosystem team.
> 
> I believe that your claims have no merit, and your further framing of our message and ad hominems at our team member do not strenghen your case.

Where did you discuss what? Sitting in front of the monitor and picking your nose? And before that, after listening to your favorite news. Which:

- When the ukrainian nazis burned people in the House of Trade Unions, they told you that it was the Russians who did it.

When the ukrainian nazis began firing mortars and anti-aircraft guns at residential buildings, schools with children and hospitals in Donbass, they told you from all the cracks that it was Russia that attacked ukraine

Wnen killed for 8 years the ukrainian fascists were engaged in killing just because you speak Russian, and your media said that this was protecting their interests and that it was the Russians who were staging genocide.

When the population of Crimea wanted to withdraw and seceded from the terrorist, imaginary state, your media called it the occupation of Crimea. Did you go to Crimea yourself and ask people about it?

When the president of this bunch of terrorists (zelinsky) supports the Nazis and gives greetings in the style of fascists together with his children, in honor of Hitler and his associates! Your media ... They're just silent! Apparently they can't think of a lie to justify it.

When the Russian troops left Bucha, the ukro-terrorists entered there as if on a hunt and shot the residents who were just walking down the street, calling it - a safari! Your media started shouting at the top of their voices that it was the Russians who killed after they left the city (idiocy).

When the ukro-terrorists entered the building of Crocus City and shot 140 people with machine guns, detonated grenades in the crowd and disappeared. Your media started saying that it's the Russians who are killing themselves like this (this is just the height of idiocy and absurdity)!!!

When your president biden declared an hour after the attack that this was not Ukraine. And you ate it with pleasure, without even thinking about how he could understand it an hour later, when at that time Russian law enforcement agencies and firefighters were fighting terrorists and trying to put out the flames.

You, as dumb, brainless animals, are shown and explained what is good and what is bad, and you, as obedient little dogs, are happy about this and accept this behavior. (!!!)

You were told that when two men fuck each other, it's good and it's a family. And a simple normal family of a man and a woman is not progressive and it depresses the positions and opinions of others. You accepted this with pleasure and began to support them on all corners by hanging out their colorful rags, waving them at your parades and processions, being proud of it.

You are told that it is necessary to protect children from violence. And yourself, in their schools, they teach sexual theory, where they offer a choice of what gender they should be, where they teach that the opinion of parents is not so important, where they assure that, in principle, there should be no moms and dads, but only parent number 1 and number 2, and maybe more... And you're protecting that, too.

You are so stupid that they can explain to you that there are  several sexes in the world, not just a man and a woman. And you, like obedient slaves, cheerfully clap your hands and shout - yes, that's it!

You, who can't see beyond your own nose, will tell me that in some bunch of your stupid like-minded people you have made some kind of decision!

All those who support terrorists, the ukro-nazis, their followers and like-minded people, the propaganda of homosexuality and the corruption of young children, all of you are for me and my like-minded people a cancerous tumor of this society.

And even if I am alone among you now, but I have kill and will continue to kill your entire ideology as much as I can at this stage of my life!!!

**Comment by atk** [comment]
> Where did you discuss what?

Discord and the banner showing our support for a global ceasefire.

Your ad hominems, anecdotal evidence, framings and unbiased claims are all only proof that you have no valid argument.

Since you have nothing to contribute to a reasonable discussion, we're past the point of responding out of courtesy, so I'll stop playing pigeon chess with you.

Have a nice life somewhere else.

**Comment by davedbase** [comment]
Thank you for your opinion.
