### ISSUE TITLE
> Where did you discuss what?

### ISSUE THREAD

**Issue by azchatlanin** [solidjs/solid-site#535]
> Where did you discuss what?

Discord and the banner showing our support for a global ceasefire.

Your ad hominems, anecdotal evidence, framings and unbiased claims are all only proof that you have no valid argument.

Since you have nothing to contribute to a reasonable discussion, we're past the point of responding out of courtesy, so I'll stop playing pigeon chess with you.

Have a nice life somewhere else.

_Originally posted by @atk in https://github.com/solidjs/solid-site/issues/525#issuecomment-2024867500_

**Comment by azchatlanin** [comment]
I am responding to your last statement:

Why didn't you mention the Gaza Strip in your banner, where thousands of people are dying?

Your banner is in support of ukraine and you know it perfectly well!

Are you a project to end the war? Or are you a World Peace organization website? No. You are the site of a development framework.

And you don't need to use it for your personal propaganda to support terrorists!

**Comment by davedbase** [comment]
Thank you for your opinion.

**Comment by betoobernal** [comment]
Many people do not value Palestinian lives, perhaps because they are not white or Caucasian, or because their fear of Jewish "economic capital" is greater.

**Comment by cos4ni2s** [comment]
You can't claim support for human lives and turn a blind eye to the literal **genocide** happening in Palestine.
Some of the core maintainers of this project are onto some agenda unfortunately. I'll give them the benifit of doubt and assume they try to attract corporate investements. Anyways I'll not be part of this whether as a user or contributor.
