### ISSUE TITLE
Typo in the Examples title

### ISSUE THREAD

**Issue by ElitoGame** [solidjs/solid-site#542]
### Describe the bug
The title of the Examples page has a typo and spells `Exanples`.

### Website link
[https://www.solidjs.com/examples/context](https://www.solidjs.com/examples/context)

### Expected behaviour
The title being spelled `Examples | SolidJS`, rather then `Exanples | SolidJS`.

**Comment by 5P5** [comment]
Sadly I do not understand the branches logic here and found no docs, so I cannot fix 🤷🏻‍♂️  but the typo is in all those:
[deploy-prod](https://github.com/solidjs/solid-site/blob/8a037d9e433c0a9b29fdb12f1a59de34bd9fbaf0/src/pages/Examples.tsx#L64C7-L64C40)
[deploy-stage](https://github.com/solidjs/solid-site/blob/f5df5e85ed4a6bd1d16bc32f3daaf56e14723d2c/src/pages/Examples.tsx#L64C6-L64C40)
[dev](https://github.com/solidjs/solid-site/blob/7dff51d5a29e53d91ff983fe9268c95cbc831ddc/src/pages/Examples.tsx#L64C7-L64C40)
