### ISSUE TITLE
Design propossal

### ISSUE THREAD

**Issue by raynerdls** [solidjs/solid-site#67]
Just wanted to share a initial mockup i'm testing for the website. I know maybe i'm late to the party, but just wanted to share some initial thoughts about the use of Call to actions buttons and the reordering of some elements of the website for adding contrast and some color (Of course this is just an opinion and more than open to review in the future).

![solid_website](https://user-images.githubusercontent.com/15605488/123772208-aaad1d80-d899-11eb-97cf-d3dfccecc846.png)

**Comment by davedbase** [comment]
Hi @raynerdls thanks so much for taking the time and pulling this together. We'll keep your concept on hand for future design iterations and concepts in case we decide to go in a different direction.
