### ISSUE TITLE
possible bug in Solve functionality for multiple tabs?

### ISSUE THREAD

**Issue by mwarger** [solidjs/solid-site#76]
https://www.loom.com/share/e0ff9435546e44f489b10a832615c63a

I had some weird behavior after trying to use the Solve button in a tutorial with multiple tabs.  You can use reset and then switch between both tabs.  After pressing Solve, the main tab is selected regardless of which was selected before, and the code for the `colored-list` component shows for "both" tabs.

**Comment by davedbase** [comment]
@modderme123 I believe you were tracking this in Discord? Is this something you or @amoutonbrady can track down for us?
