### ISSUE TITLE
The docs page is very heavy to load

### ISSUE THREAD

**Issue by aminya** [solidjs/solid-site#79]
Currently, all the docs are rendered on a single page, which takes a long time to load. This is especially noticeable on mobile.

My suggestion is to dynamically render the sections on demand instead of rendering all of them on a long page. The `content` here should be only the content of one section.
https://github.com/solidjs/solid-site/blob/bfb2862eb1e423c59d8f02c17612eb6a0de8e027/src/pages/Docs.tsx#L133

**Comment by davedbase** [comment]
Yeah I'm also concerned about this. I think dynamic rendering would be tricky. Depending how we handle it, could have consequences for SEO and usability. I'm wondering if we should just separate them into separate pages as a dropdown from the Docs.

**Comment by aminya** [comment]
Yes, we should have separate pages.

**Comment by davedbase** [comment]
I'm considering this structure:

`1. Get Started (All one page containing our "guides")`
  - Try Solid
  - Learn Solid
  - Think Solid
  - Web Components
  - Server Rendering
  - No Compilation? (Maybe ask Ryan to change the name)

`2. Docs (All non guides listed above)`

This basically splits the page into two sections that will serve up only the above listed content.

**Comment by ryansolid** [comment]
The Guide should include
Getting Started
Reactivity
Rendering
Server

What you have there is only Getting Started.

**Comment by davedbase** [comment]
Yup good point. Ok well we'll start implementing this then.

**Comment by davedbase** [comment]
Guides and docs are now separate. The page is still heavy but not *as* heavy. Currently on dev: https://dev.solidjs.com/ but available soon on prod.
