### ISSUE TITLE
Code view not scrolling to top when changing articles

### ISSUE THREAD

**Issue by Sawtaytoes** [solidjs/solid-site#82]
When I click an article in the dropdown, the code view doesn't scroll to the top as shown in this example:

![image](https://user-images.githubusercontent.com/3948069/124208440-26cb7f00-daad-11eb-826f-a669050c3fac.png)

**Comment by davedbase** [comment]
@amoutonbrady @modderme123 does the REPL have a way to trigger this?

**Comment by amoutonbrady** [comment]
There's currently no way to do that but that's a good feature to have. I'll investigate see how hard that would be to had a manual trigger or/and an automatic one.

**Comment by amoutonbrady** [comment]
@davedbase @modderme123 I just released `solid-repl` @0.13.0. In this version you have a new props for the `<Repl />` component: `onEditorReady` which is a function that exposes the MonacoEditor instance when ready.

According to [this stackoverflow](https://stackoverflow.com/questions/45123386/scroll-to-line-in-monaco-editor), this should be sufficient for you manually scroll the editor back to top (or any other line really) whenever you feel like it.

**Comment by davedbase** [comment]
Got it. Deploying with next release.
