### ISSUE TITLE
Docs: Ambigious/unclear wording in Bindings/Events

### ISSUE THREAD

**Issue by dsone** [solidjs/solid-site#92]
https://www.solidjs.com/tutorial/bindings_events
> All on bindings are **case insensitive** which means that event **names need to be in lowercase**.

This is  a bit confusing. Maybe it's my late local time, maybe the text. But case insensitivity means `TEXT` and `text` are considered to be the same. So `onmousemove` is the same as `onMouSEMove`. The example code, however, is using lower camel case. Not lower case. If I change the code to this (small first m):
```javascript
<div onmouseMove={handleMouseMove}>
      The mouse position is {pos().x} x {pos().y}
</div>
```
The code window underlines the `onmouseMove` telling me 
> Property 'onmouseMove' does not exist on type 'HTMLAttributes<HTMLDivElement>'. Did you mean 'onMouseMove'?

But If I use entirely lowercase `onmousemove` it is not underlined.
The code works either way in the bottom right.

I am not sure what is supposed to be "lowercase" and why when the events on the lesson are not used as lowercase and the code works either way. Or is it meant that to trigger those events manually you need to use the lower case name? But then again, if the events are case insensitive, why do they need to be lower case?
Am I just confused or is the wording off?

**Comment by ryansolid** [comment]
It doesn't matter. I went for case insensitive on native elements to mirror the DOM. Some people prefer to use it that way. But TypeScript of course wants things so I added both all lowercase and typical React Style Camel Case. The other permutations work but TypeScript will complain.

**Comment by dsone** [comment]
Ah, thanks, that makes sense. So, I do not have to particularly bother with the casings as a beginner in Solid yet.
To make the lesson clearer, I'd argue it'd be beneficial to mention that there as well. As it stands the quoted line seems contradictory otherwise.
I'd pull request that but I am not comfortable enough in Solid/TS to get the intended meaning across properly, though.
