### ISSUE TITLE
Tutorial solutions for Binding/Refs & Binding/Forwarding refs potentially confusing 

### ISSUE THREAD

**Issue by bobaekang** [solidjs/solid-site#96]
The [Binding/Refs tutorial](https://www.solidjs.com/tutorial/bindings_refs) and the [Binding/Forwarding refs tutorial](https://www.solidjs.com/tutorial/bindings_forward_refs) feature a canvas element where the animation could be applied during `onMount()`. This leads to a behavior that is potentially confusion while completely valid: i.e. the user does not see the animation when the solution is applied because `onMount()` does not rerun. Forcing the component to be re-mounted, e.g. switching tabs to `Output` and back to `Result`, shows the animation. 

While this is fair and as expected, some users might still find it confusing that applying the solution does not immediately lead to the animation going in effect. My suggestion is to include some kind of a "refresh" icon/button on "Result" tab that can be used to quickly re-mount the component without leaving the "Result" tab. Alternatively, the tutorial may include some additional text to instruct users to force re-mounting the component.

**Comment by ryansolid** [comment]
I don't think the exampke is at fault. It should rerun it all. I think this is a symptom of one of the bugs that is being looked into in the REPL.

**Comment by bobaekang** [comment]
@ryansolid

To clarify, I did not meat to say that the tutorial example is faulty. Perhaps this is due to my lack of understanding re: the inner workings of the tutorial page, but I actually thought that it made sense the animation did not show when the code changed. I.e. the component was already mounted so it made sense that `onMount()` was not invoked again.

If fixing another issue with REPL would change this behavior, that'd be great too. In that case, should I expect that changing the code (i.e. recompiling) always leads to re-mounting the Solid components?

**Comment by ryansolid** [comment]
In the REPL environment yes. I was guessing even with normal HMR that's pretty typical, but maybe not. We don't know what you changed it should remount the whole component. Honestly, there are complexities in maintaining state I haven't figured out mostly that Solid needs to run the computations to track dependencies but at least for the foreseeable future I think you should expect the component to remount.
