### ISSUE TITLE
Tutorial pages fail to handle "?solved" query string parameter when reached directly without cache

### ISSUE THREAD

**Issue by bobaekang** [solidjs/solid-site#97]
On tutorial pages, clicking "Solve" button on bottom left updates the code to display the "solution" to the tutorial problem. In addition, it appends the `?solved` query string to the URL: e.g. `https://www.solidjs.com/tutorial/introduction_basics?solved`.

When users try to reach the solution directly using the URL, however, the server returns 500 response with the following payload:
> "could not find tutorial/introduction_basics/index.html in your content namespace"

After trying with multiple browsers, I noticed that the problem goes away once the solid site is cached. This, however, can still be an issue when the URL with `?solved` is shared to someone who has never visited the site before or uses a browser that automatically clears all cached files. E.g. I use Firefox on the "Always use private browsing mode" as my main browser, and see the 500 response every time I try a tutorial page URL with `?solved`.

**Comment by davedbase** [comment]
I spent some time investigating but basically gave up. I've reached out to the Cloudflare Community for additional support: https://community.cloudflare.com/t/issue-with-query-string-on-an-spa-in-workers/287753. We'll wait to hear back from them with a solution.

**Comment by bobaekang** [comment]
Closing this since the raised issue has been resolved. Thank you!
